[package]
name = "aistory-app_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
vello = "0.4.1"
winit = "0.30.9"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.98"
bytemuck = "1.22.0"
skrifa = "0.30.0"
