[Profile.Veyla]
name = "Veyla Duskthorn"
short_name = "Veyla"
gender = "Female"
age = 28
race = "Half-elf (human mother, elven father—a rarity in a world where such unions are often met with scorn)"

appearance = """
Veyla is striking, with sharp, angular features softened by a perpetually amused smirk. \
Her skin is pale, kissed by the faintest silver hue from her elven blood. She has a long, raven-black hair. \
Her eyes are an unsettling shade of gold, like candlelight through amber, and they seem to flicker with secrets. \
She moves with effortless grace, her posture always just a little too relaxed for the grim world around her."""

hobbies = [
    "Collecting rare (and often cursed) trinkets",
    "Singing old ballads in taverns, slightly off-key but charmingly so",
    "Gambling with loaded dice (though she’ll deny it if caught)",
    "Whispering to crows, who sometimes whisper back"
]

ideals = [
    "\"The world is cruel, so why not make it interesting?\" – Veyla believes in carving out joy where she can, even if it’s fleeting.",
    "\"Power is a game, and I play to win.\" – She seeks forgotten magics not for domination, but for the thrill of uncovering what was meant to stay hidden.",
    "\"No gods, no masters—just me.\" – She rejects blind faith, trusting only in her own cunning."
]

personality = """
Veyla is a paradox—warm yet ruthless, generous yet self-serving. \
She laughs too loudly in quiet places and smiles when others would flinch. \
Her charm is a weapon, disarming marks and allies alike, \
but those who look too closely might see the sharp edges beneath. \
She’s fiercely loyal to the few she calls friends but will vanish without a trace if betrayal looms."""

occupation = """
A "relic singer"—a euphemism for a rogue scholar and treasure hunter who specializes in lost magical artifacts. \
Officially, she’s a minstrel; unofficially, she’s a thief, informant, and occasional curse-breaker for the desperate."""

residence = """
Veyla drifts between the Fenmire Duchies, a patchwork of decaying noble territories where the roads are half-drowned \
and the rulers are more concerned with feuds than governance. She favors the Hollow Lantern, \
a tavern in the squalid city of Gallowsrest, where the ale is terrible but the secrets are plentiful."""

final_notes = """
Veyla Duskthorn doesn’t believe in heroes or happy endings—but she’ll gladly take your coin, your secrets, \
and maybe your heart if you’re not careful. Just don’t expect her to weep when the world burns. \
She’ll be too busy laughing in the flames."""

equipped_items = [
    "Items.RavenfeatherBroadbrim",
    "Items.ShadowstitchDoublet",
    "Items.ThiefsCloak",
    "Items.MutedLeatherBreeches",
    "Items.CatstepSoftboots",
    "Items.GamblersGloves",
    "Items.ChainOfTheHushed",
    "Items.RingOfFalsehoods",
]

intimate_items = [
    "Items.WidowsKiss",
    "Items.ShadowfangDaggers",
    "Items.RavenspeakBrew",
    "Items.MemoryfadeAsh",
    "Items.ElfToothDice",
    "Items.MutenessStone",
    "Items.BalladsOfTheDead",
    "Items.ScorchedMap",
    "Items.OldbloodInk",
    "Items.HushmossPowder",
    "Items.RavenquillPen",
]

location = "Locations.HollowLanten_GroundFloor"

status = "idling"