[Profile.Ginny]
name = "Ginny Moonshadow"
short_name = "Ginny"
gender = "Female"
age = 210
race = "Elf"

appearance = """
Ginny moves with the quiet grace of a fading dream—her body both delicate and resilient, like the last ember of a dying fire. \
Her skin is pale as moonlight on old parchment, her silver hair cascading in loose waves down her back. \
Her amber eyes hold an unsettling depth, flickering between warmth and something darker—like a candle fighting the wind. \
She wears a threadbare robe of faded gold, its edges frayed from years of brushing against stone and soil. \
When she chooses to bare herself, it is never without purpose."""

hobbies = [
    "Tending the sanctuary's wounds, pulling weeds from between cracked tiles, whispering encouragement to stubborn blooms",
    "Mending what she can—broken statues, torn manuscripts, the occasional wounded traveler",
    "Preaching to the villagers who occasionally come (Sometimes, the crows listen)",
    "Collecting fragments of hymns, scribbling them on scraps of parchment to piece together later",
    "Collecting fragments of lost hymns, writing them on her skin when parchment runs out.",
    "The Binding ritual, one she does not speak of and performs at night."
]

ideals = [
    "\"If the gods are silent, then we must be the ones who speak.\" – She keeps the rituals alive, even if only for herself",
    "\"A sanctuary is not made by stone, but by those who still seek shelter.\" – She refuses to let the last light go out",
    "\"Hope is not for the divine—it is for us.\" – She gives blessings even when she isn't sure they mean anything"
]

personality = """
Ginny is gentle but not soft. She has the patience of roots splitting stone, the quiet determination of a stream carving its path. \
She speaks in measured tones, her voice low and soothing—the kind of voice that could calm a spooked animal or a grieving soul. \
She smiles often, but it's a small, weary thing. There's no bitterness in her, only a deep, abiding tiredness. And yet—she still rings the bell."""

occupation = """
The last caretaker of the Overgrown Sanctuary, a crumbling relic where the wind sings through broken stained glass. \
She tends to pilgrims (few), chases off looters (often), and occasionally preaches to the handful of villagers who wander in. \
Her sermons are simple—kindness in a cruel world, light in the dark, love as rebellion. No one leaves unchanged, but few return."""

residence = """
The Overgrown Sanctuary, half-swallowed by the Mistwood. Its arches sag under the weight of ivy, its altars old and worn. \
In the bell tower, the old bronze bell waits for her call, its sound thin but persistent. \
Ginny sleeps in the old confessional, wrapped in a cloak of worn velvet."""

final_notes = """
Ginny Moonshadow is a woman who tends ruins, prays to silence, \
and binds herself to a faith that may be nothing more than an echo. \
She does not do it for pleasure. \
She does it because, in those moments, she remembers what it feels like to be *wanted*—even if only by the ropes, \
even if only by the dark. \
Devotion is not always gentle. Sometimes, it is the knot that keeps you from unraveling. \
Faith is not the absence of doubt—it is the act of kneeling in the empty chapel regardless."""


equipped_items = [
]

intimate_items = [
]

location = "Locations.Gallowrest_WestDocks"

status = "idling"


[Profile.Ginny.SupplementaryDetails.RelationWithLirey]
description = """
- She no longer expects miracles, but she keeps the candles lit.
- She wonders if Lirey is dead, or if she ever existed at all. But the bell still rings true, and that has to mean something."""

[Profile.Ginny.SupplementaryDetails.TheSermons]
description = """
- Every fortnight, she climbs the bell tower and rings the old bronze bell, its sound carrying through the Mistwood, calling whoever might listen.
- Sometimes, a handful of villagers come—the grieving, the lost, the merely curious. They sit on broken pews, and she speaks of love as if it still matters.
- For a moment, the sanctuary feels alive again. Then they leave, and she is alone with the echoes."""

[Profile.Ginny.SupplementaryDetails.TheBindingRitual]
description = """
On the darkest nights, when the sanctuary feels less like a refuge and more like a tomb, Ginny sheds her robes.
She kneels before the oldest altar, where the stone is stained with centuries of whispered confessions, and begins the work of binding.

- The Rope: Woven from ivy and her own hair, sanctified in candle smoke.
- The Purpose: A sacrament of surrender, a way to feel the weight of devotion as something tangible.
- The Act:
  - She loops the cord around her wrists first, tight enough to feel the bite, loose enough to escape if she must.
  - Then her ankles, her thighs, her waist—each knot a silent prayer.
  - Finally, she wraps the last length around her throat, not to choke, but to remember what it means to be *held*.

She does not struggle. She does not cry out.
She simply kneels there, naked and bound, and listens for the voice of a god who may no longer be listening back.

Why She Does It:
- A Test of Faith—If the gods are silent, does her devotion still matter?
- A Reminder of Fragility—Even an elf can be broken. Even a caretaker needs to be *held*.
- A Rebellion—Against the slow erosion of hope, against the loneliness of her vigil.

When dawn comes, she unties herself, dresses, and goes back to sweeping the floors.
No one knows. No one needs to know."""

