[Wiki.World]
description = """
This is a dark medieval low-magic fantasy world. This is not a world on the brink of collapse. \
The light is faint, but it flickers still. The arcane is fading—now scarce, demanding, sometimes consuming. \
Races that once relied on magic struggle to maintain their existence and glory. Gods are a distant illusion, \
existence never known. Magics and races except for human are rather rare now. Society is defined by low productivity, \
isolated communities, and rigid hierarchies. Everyday life is a struggle for many. \
Yet light, howsoever feeble, lingers in the deepest dark."""